version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/wordpress"
    schedule:
      interval: "daily"
    labels:
      - "automerge"
    allow:
      - dependency-name: "wordpress"
    commit-message:
      prefix: "[npp-bot]"

  - package-ecosystem: "docker"
    directory: "/mysql"
    schedule:
      interval: "daily"
    labels:
      - "automerge"
    allow:
      - dependency-name: "mysql"
    commit-message:
      prefix: "[npp-bot]"

  - package-ecosystem: "docker"
    directory: "/nginx"
    schedule:
      interval: "daily"
    labels:
      - "automerge"
    allow:
      - dependency-name: "nginx"
    commit-message:
      prefix: "[npp-bot]"

  - package-ecosystem: "docker"
    directory: "/phpmyadmin"
    schedule:
      interval: "daily"
    labels:
      - "automerge"
    allow:
      - dependency-name: "phpmyadmin"
    commit-message:
      prefix: "[npp-bot]"
