version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/wordpress"
    schedule:
      interval: "daily"
    labels:
      - automerge
    allow:
      - dependency-name: "wordpress"

  - package-ecosystem: "docker"
    directory: "/mysql"
    schedule:
      interval: "daily"
    labels:
      - automerge
    allow:
      - dependency-name: "mysql"

  - package-ecosystem: "docker"
    directory: "/nginx"
    schedule:
      interval: "daily"
    labels:
      - automerge
    allow:
      - dependency-name: "nginx"
