version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/wordpress"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "wordpress"
    automerge: true

  - package-ecosystem: "docker"
    directory: "/mysql"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "mysql"
    automerge: true

  - package-ecosystem: "docker"
    directory: "/nginx"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "nginx"
    automerge: true
