name: Cleanup untagged GHCR images

on:
  schedule:
    - cron: '30 1 * * 0'
  workflow_dispatch:

jobs:
  ghcr-cleanup:
    name: GHCR cleanup
    runs-on: ubuntu-latest
    permissions:
      packages: write
    concurrency:
      group: cleanup-images

    steps:
      - name: Dry run - show what would be deleted
        uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          packages: >-
            wordpress-nginx-cache-docker/wordpress,
            wordpress-nginx-cache-docker/mysql,
            wordpress-nginx-cache-docker/nginx,
            wordpress-nginx-cache-docker/phpmyadmin,
            wordpress-nginx-cache-docker/mitmproxy,
            wordpress-nginx-cache-docker/redis
          delete-untagged: true
          dry-run: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Delete untagged images
        uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          packages: >-
            wordpress-nginx-cache-docker/wordpress,
            wordpress-nginx-cache-docker/mysql,
            wordpress-nginx-cache-docker/nginx,
            wordpress-nginx-cache-docker/phpmyadmin,
            wordpress-nginx-cache-docker/mitmproxy,
            wordpress-nginx-cache-docker/redis
          delete-untagged: true
          dry-run: false
          validate: true
          token: ${{ secrets.GITHUB_TOKEN }}
